In [10]:
import numpy as np
import pandas as pd
import time
from sklearn import preprocessing

In [11]:
# 存储数据的根目录
ROOT_PATH = "/testcbd017_gujinfang/GJFCode/WeChat_2021/Code/data"
SUB_PATH=ROOT_PATH+'/submit'

In [12]:
subset={
#     SUB_PATH+'/sub_wdl_des_tag_keyword_pair_8.csv':5,
        SUB_PATH+'/b_tree_1.csv':[4,4.4,7,7],
        SUB_PATH+'/b_tree_2.csv':[4,4.4,7,7],
        SUB_PATH+'/b_deepfm1_3.csv':[3.5,0,0,0],
        SUB_PATH+'/b_deepfm2_3.csv':[3.5,0,0,0],
        SUB_PATH+'/b_sub_nn_1_5.csv':[1,1,1.1,1.1],
        SUB_PATH+'/b_sub_nn_2_5.csv':[1,1,1.1,1.1],
        SUB_PATH+'/b_sub_nn_3_5.csv':[1,1,1.1,1.1],
        SUB_PATH+'/b_sub_nn_4_5.csv':[1,1,1.1,1.1],
        SUB_PATH+'/b_sub_nn_5_5.csv':[1,1,1.1,1.1],
        SUB_PATH+'/b_sub_nn_6_5.csv':[1,1,1.1,1.1],
        SUB_PATH+'/b_sub_nn_7_5.csv':[1,1,1.1,1.1],
        SUB_PATH+'/b_sub_nn_8_5.csv':[1,1,1.1,1.1],
}

In [13]:
submit_final=pd.DataFrame()
min_max_scaler = preprocessing.MinMaxScaler(feature_range=(0., 1.))
cols=["read_comment", "like", "click_avatar",  "forward"] # 需要归一化的列
base_cols=['userid','feedid']

In [13]:
# # 归一化提交结果权重
# weights=list(subset.values())
# weights=[w/sum(weights) for w in weights]
# subset=dict(zip(subset.keys(),weights))
# # print(subset)

In [14]:
values_cols=[]
# 计算融合结果
for file_path,weight in subset.items():
    print(weight)
    cur_submit=pd.read_csv(file_path)
    submit_final[base_cols]=cur_submit[base_cols]
    cur_values=min_max_scaler.fit_transform(cur_submit[cols].values)
#     print(cur_values[:5,:])
    if(values_cols==[]):
        values_cols=np.array([[0.]*len(cols)]*len(cur_submit))
    print(cur_values)
    values_cols+=cur_values*weight
# print(values_cols[:5,:])

[4, 4.4, 7, 7]
[[7.01230964e-03 2.95671881e-03 4.92595127e-03 4.96807010e-04]
 [2.93581953e-03 1.76452835e-02 2.01775342e-03 1.41180687e-03]
 [5.52905009e-06 1.73432087e-03 1.16498216e-03 2.98288330e-04]
 ...
 [4.15818459e-02 1.94387578e-03 9.82747190e-03 1.41822454e-03]
 [2.25941410e-02 2.40558366e-02 1.07844225e-02 8.28467078e-03]
 [9.85741517e-06 8.81695800e-03 3.77754732e-03 5.03459817e-04]]
[4, 4.4, 7, 7]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if __name__ == '__main__':


[[6.22326147e-03 2.47096939e-03 1.00675233e-03 0.00000000e+00]
 [2.94681758e-03 1.77927587e-02 0.00000000e+00 3.10795515e-04]
 [2.24514027e-05 1.90326022e-03 0.00000000e+00 0.00000000e+00]
 ...
 [4.68022776e-02 1.68565974e-03 2.97065425e-03 5.56254669e-04]
 [2.05726462e-02 2.07510675e-02 4.56550481e-03 1.63341776e-03]
 [2.79329672e-05 9.49926758e-03 0.00000000e+00 3.93990976e-05]]
[3.5, 0, 0, 0]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if __name__ == '__main__':


[[0.00430212 0.01154039 0.03661934 0.00910949]
 [0.00192058 0.04389747 0.0193064  0.01712973]
 [0.00033847 0.01084902 0.00876714 0.01104756]
 ...
 [0.05054628 0.00257175 0.11445205 0.02539553]
 [0.02650182 0.0273972  0.10846201 0.0450636 ]
 [0.0019235  0.0192719  0.04040539 0.01238075]]
[3.5, 0, 0, 0]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if __name__ == '__main__':


[[0.00606793 0.01366738 0.04342634 0.0073972 ]
 [0.00072508 0.04854558 0.02780469 0.01293749]
 [0.00018829 0.01175118 0.01110258 0.01376365]
 ...
 [0.03140305 0.00254602 0.14794914 0.0213555 ]
 [0.02413227 0.03872008 0.15728363 0.04326042]
 [0.00119604 0.02348819 0.03692948 0.01082418]]
[1, 1, 1.1, 1.1]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if __name__ == '__main__':


[[0.0060037  0.02078571 0.03715059 0.00817702]
 [0.00096693 0.04301634 0.01586748 0.01203362]
 [0.00018862 0.00974878 0.00744268 0.00683391]
 ...
 [0.03370539 0.00665377 0.0825184  0.01923165]
 [0.01836286 0.04078065 0.11177064 0.07507452]
 [0.00050275 0.02902845 0.02345828 0.01472894]]
[1, 1, 1.1, 1.1]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if __name__ == '__main__':


[[0.00810842 0.01934274 0.03605878 0.00823909]
 [0.00152204 0.04775683 0.01276419 0.02116586]
 [0.0006735  0.00527134 0.00486969 0.00873614]
 ...
 [0.03553204 0.0076129  0.09338765 0.0150293 ]
 [0.01410106 0.03229487 0.1070739  0.06809056]
 [0.00103715 0.02785862 0.02035012 0.01942926]]
[1, 1, 1.1, 1.1]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if __name__ == '__main__':


[[0.00578965 0.03597035 0.0411883  0.00524907]
 [0.00139883 0.04257583 0.00709722 0.01331765]
 [0.00044471 0.0134358  0.0035459  0.00485938]
 ...
 [0.05252577 0.01260874 0.08420598 0.01241803]
 [0.01987847 0.03586099 0.08171558 0.08146632]
 [0.00174486 0.04554551 0.03183156 0.01534929]]
[1, 1, 1.1, 1.1]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if __name__ == '__main__':


[[0.00778362 0.01982736 0.03198647 0.006293  ]
 [0.00081394 0.04226053 0.0147163  0.01143361]
 [0.00025846 0.00715697 0.00491975 0.00414041]
 ...
 [0.03867425 0.00348166 0.06699495 0.01071506]
 [0.01040833 0.02588215 0.09484887 0.03411037]
 [0.00121079 0.02236002 0.02184764 0.01009985]]
[1, 1, 1.1, 1.1]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if __name__ == '__main__':


[[0.0086882  0.02582352 0.03162961 0.02606959]
 [0.00142839 0.0520518  0.01677043 0.00942557]
 [0.00059879 0.00964018 0.00364614 0.00705806]
 ...
 [0.03829091 0.00785155 0.09341563 0.01728106]
 [0.02240375 0.05323712 0.09313588 0.07633398]
 [0.00167543 0.03017142 0.01927675 0.01183807]]
[1, 1, 1.1, 1.1]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if __name__ == '__main__':


[[0.0088547  0.02443554 0.03915801 0.0083481 ]
 [0.00284974 0.03854062 0.01681283 0.01381187]
 [0.00110015 0.0084273  0.00621303 0.00848872]
 ...
 [0.06569267 0.01019569 0.08443961 0.01132932]
 [0.02231967 0.03303766 0.06590907 0.0630404 ]
 [0.00343    0.02628728 0.01996581 0.02309845]]
[1, 1, 1.1, 1.1]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if __name__ == '__main__':


[[0.00205961 0.01788734 0.01876449 0.00685446]
 [0.00083781 0.05228995 0.00761628 0.00983109]
 [0.00027724 0.00444852 0.0053677  0.01077663]
 ...
 [0.04695359 0.00513111 0.0665107  0.02881838]
 [0.01587876 0.03477802 0.06937162 0.05280558]
 [0.00193879 0.02193726 0.03630277 0.01265259]]
[1, 1, 1.1, 1.1]
[[0.00825385 0.02473193 0.0316063  0.01251289]
 [0.00082007 0.0421253  0.00894425 0.01756117]
 [0.00042807 0.00798808 0.00421438 0.00952629]
 ...
 [0.02208438 0.01094633 0.07456679 0.01905768]
 [0.01300982 0.03105711 0.10696028 0.05126078]
 [0.00112219 0.03357832 0.01345953 0.0236475 ]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if __name__ == '__main__':


In [15]:
print(values_cols)

[[0.14477923 0.21268632 0.33582574 0.0933952 ]
 [0.04342811 0.51654456 0.12477215 0.13149671]
 [0.00592514 0.08212233 0.05239608 0.0685495 ]
 ...
 [0.97381816 0.08045172 0.80023056 0.16108989]
 [0.48624917 0.48407895 0.91131392 0.6218274 ]
 [0.02373153 0.31735827 0.23158454 0.14772836]]


In [16]:
submit_final[cols]=min_max_scaler.fit_transform(values_cols)

In [17]:
print(submit_final.head())

   userid  feedid  read_comment      like  click_avatar   forward
0  116490   18545      0.006264  0.012490      0.016751  0.004232
1   19265   53010      0.001848  0.030635      0.006175  0.006004
2  194374    9003      0.000214  0.004693      0.002549  0.003077
3   19414   75730      0.001022  0.003875      0.036305  0.001415
4    6434   17863      0.006429  0.099898      0.130708  0.065125


In [18]:
save_path='{}/b_sub_nn_tree_{}model_{}.csv'.format(SUB_PATH,len(subset),'1')
submit_final.to_csv(save_path,index=False)

In [3]:
a=[1,0,3]
a=np.array(a)
b=np.arange(12).reshape((4,3))

In [4]:
print(a)
print(b)
print(a*b)

[1 0 3]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  0  6]
 [ 3  0 15]
 [ 6  0 24]
 [ 9  0 33]]
